#image: golang:1.18

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  DOCKER_REGISTRY: $DOCKER_REGISTRY
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  AWS_REGION: eu-central-1
  AWS_CLUSTER_NAME: $AWS_CLUSTER_NAME
  APP_NAME: locg_service
  NAMESPACE: $NAMESPACE
  VERIFY_CHECKSUM: 'false'
  DOCKER_HOST: $DOCKER_HOST
  DATABASE_NAME: $DATABASE_NAME
  DATABASE_HOST: $DATABASE_HOST
  DATABASE_NAME_GAME: $DATABASE_NAME_GAME
  DATABASE_USERNAME: $DATABASE_USERNAME
  DATABASE_PASSWORD: $DATABASE_PASSWORD
  ENVIRONMENT: $CI_COMMIT_BRANCH
  BLOCKCHAIN_MINTER_PRIVATE_KEY: $BLOCKCHAIN_MINTER_PRIVATE_KEY
  PAYPAL_CLIENT_ID: $PAYPAL_CLIENT_ID
  PAYPAL_SECRET: $PAYPAL_SECRET
  OVERRIDE_CONFIG_BRANCH: $OVERRIDE_CONFIG

stages:
  - build
  - deploy

docker-build:
  stage: build
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  services:
    - name: docker:25-dind
      alias: docker
      entrypoint: ['dockerd-entrypoint.sh', '--tls=false']

  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
    - echo $CI_COMMIT_BRANCH
    - aws sts get-session-token
    - echo $DOCKER_REGISTRY
    - aws ecr --region eu-central-1 get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - docker build --build-arg CI_COMMIT_BRANCH=${CI_COMMIT_BRANCH} --build-arg CI_COMMIT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg CI_PROJECT_URL=${CI_PROJECT_URL} --build-arg BUILD_NUMBER=${CI_PIPELINE_ID} -t "$DOCKER_REGISTRY:${CI_COMMIT_BRANCH}-latest" .
    - docker push "$DOCKER_REGISTRY:${CI_COMMIT_BRANCH}-latest"
  environment:
    name: $CI_COMMIT_BRANCH
  only:
    - web
    - development
    - staging
    - production
  except:
    - schedules
    - test-feature-branch

deploy-dev:
  stage: deploy
  image: kroniak/ssh-client
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > env.sh
    - echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> env.sh
    - echo "export DOCKER_REGISTRY=$DOCKER_REGISTRY" >> env.sh
    - echo "export DATABASE_USERNAME=$DATABASE_USERNAME" >> env.sh
    - echo "export DATABASE_PASSWORD=$DATABASE_PASSWORD" >> env.sh
    - echo "export DATABASE_HOST=$DATABASE_HOST" >> env.sh
    - echo "export DATABASE_NAME=$DATABASE_NAME" >> env.sh
    - echo "export PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID" >> env.sh
    - echo "export PAYPAL_SECRET=$PAYPAL_SECRET" >> env.sh
    - echo "export BLOCKCHAIN_MINTER_PRIVATE_KEY=$BLOCKCHAIN_MINTER_PRIVATE_KEY" >> env.sh
    - echo "export IMAGE_TAG=${CI_COMMIT_BRANCH}-latest" >> env.sh
    - echo "export BRANCH=${CI_COMMIT_BRANCH}" >> env.sh
    - ssh ubuntu@$SSH_ADDRESS -o StrictHostKeyChecking=no "mkdir -p ~/locg"
    - scp -o StrictHostKeyChecking=no env.sh ubuntu@$SSH_ADDRESS:~/locg/env.sh
    - scp -o StrictHostKeyChecking=no -r deploy/ ubuntu@$SSH_ADDRESS:~/locg
    - ssh ubuntu@$SSH_ADDRESS -o StrictHostKeyChecking=no "chmod +x ~/locg/env.sh"
    - ssh ubuntu@$SSH_ADDRESS -o StrictHostKeyChecking=no "aws ecr --region eu-central-1 get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY"
    - ssh ubuntu@$SSH_ADDRESS -o StrictHostKeyChecking=no "source ~/locg/env.sh && source ~/locg/deploy/functions.sh && locg_delete_environment development && locg_deploy development ${CI_COMMIT_SHORT_SHA}"
  dependencies: []
  environment:
    name: ${CI_COMMIT_BRANCH}
  only:
    - development
    - production
  when: manual
  except:
    - schedules

stop_environment:
  stage: deploy
  image: kroniak/ssh-client
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - scp -o StrictHostKeyChecking=no -r deploy/ ubuntu@$SSH_ADDRESS:~/locg
    - ssh ubuntu@$SSH_ADDRESS -o StrictHostKeyChecking=no "source ~/locg/deploy/functions.sh && locg_delete_environment ${CI_COMMIT_BRANCH}"
  environment:
    name: $CI_COMMIT_BRANCH
    action: stop
  dependencies: []
  only:
    - web
    - production
    - development
  except:
    - tags
    - schedules
  when: manual

