version: '3.5'
services:
  nats:
    restart: always
    networks:
      - locg_app_network
    image: 'nats:alpine'
    ports:
      - '4222:4222'
  redis:
    restart: always
    networks:
      - locg_app_network
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  # service:
  #   restart: always
  #   networks:
  #     - locg_app_network
  #     - internal_${ENVIRONMENT}
  #   image: '696215560370.dkr.ecr.eu-central-1.amazonaws.com/game-backend-dev:${IMAGE_TAG}'
  #   ports:
  #     - '${HTTP_PORT}:8080'
  #   environment:
  #     DATABASE_DATABASE_GAME: ${DATABASE_NAME_GAME}
  #     DATABASE_HOST_GAME: game-dev.icpjq.mongodb.net
  #     DATABASE_HOST: marketplace.ikhxlro.mongodb.net
  #     DATABASE_DATABASE: ${DATABASE_NAME}
  #     DATABASE_PORT: '27017'
  #     DATABASE_USERNAME: ${DATABASE_USERNAME}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     REDIS_HOST: 'redis'
  #     REDIS_PORT: '6379'
  #     NATS_ADDRESS: 'nats:4222'
  #     NETWORK_VERBOSE_MODE: 'false'
  #     ENVIRONMENT: ${ENVIRONMENT}
  #     AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  #     AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  #     BLOCKCHAIN_MINTER_PRIVATE_KEY: ${BLOCKCHAIN_MINTER_PRIVATE_KEY}
  #   links:
  #     - 'nats:nats'
  #     # - 'mongodb:mongodb'
  #     - 'redis:redis'

  # jobs-service:
  #   restart: always
  #   networks:
  #     - locg_app_network
  #     # - internal_dev
  #   build:
  #     context: ../
  #     dockerfile: ./.devcontainer/Dockerfile
  #   environment:
  #     DATABASE_HOST: game-dev.icpjq.mongodb.net
  #     DATABASE_DATABASE: ${DATABASE_DATABASE}
  #     DATABASE_PORT: '27017'
  #     DATABASE_USERNAME: "locdev"
  #     DATABASE_PASSWORD: 'bf2x4pkf4f'
  #     REDIS_HOST: "locg_development-redis-1"
  #     REDIS_PORT: '6379'
  #     NATS_ADDRESS: 'nats:4222'
  #     NETWORK_VERBOSE_MODE: 'false'
  #     ENVIRONMENT: 'development'
  #     BRANCH: 'development'
  #     AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  #     AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  #     BLOCKCHAIN_MINTER_PRIVATE_KEY: ${BLOCKCHAIN_MINTER_PRIVATE_KEY}
  #   links:
  #     - 'nats:nats'
  #     - 'redis:redis'
networks:
  locg_app_network:
    name: 'locg_dev_network'
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'true'
  internal:
    name: 'internal_dev'
    external: true
