---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locg-rest-api
  namespace: locg-prod
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: locg-rest-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: locg-rest-api
    spec:
      containers:
        - name: locg-rest-api
          image: '696215560370.dkr.ecr.eu-central-1.amazonaws.com/go-rest-api:dev'
          ports:
            - name: ws-locg
              containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: 'production'
            - name: BRANCH
              value: 'production'
            - name: REDIS_HOST
              value: 'locg-redis-master'
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: locg-redis
                  key: redis-password
                  optional: false
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: locg-secrets
                  key: aws-access-key-id
                  optional: false
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: locg-secrets
                  key: aws-secret-access-key
                  optional: false
            - name: BLOCKCHAIN_MINTER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: locg-secrets
                  key: blockchain-minter-private-key
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: locg-secrets
                  key: paypal-client-id
            - name: PAYPAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: locg-secrets
                  key: paypal-secret
                  optional: false
            - name: DATABASE_HOST
              value: 'cluster0.3mf83x6.mongodb.net'
            - name: DATABASE_DATABASE
              value: 'locg_production'
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: locg-secrets
                  key: database-username
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: locg-secrets
                  key: database-password
                  optional: false
            - name: NATS_ADDRESS
              value: 'locg-nats:4222'
