apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: staging-backend
  region: eu-central-1

vpc:
  id: vpc-00302105d300ce713
  subnets:
    private:
      eu-central-1a: { id: subnet-0167f6dfa3c69077a }
      eu-central-1b: { id: subnet-025bf8aaf5aee1f74 }
      eu-central-1c: { id: subnet-01b26357b0fe1b2dc }

managedNodeGroups:
  - name: mng-1
    instanceType: t3a.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    privateNetworking: true
    availabilityZones: ['eu-central-1a', 'eu-central-1b', 'eu-central-1c']
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ['audit', 'authenticator', 'controllerManager']
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
