apiVersion: v1
kind: Service
metadata:
  name: locg-service
spec:
  type: NodePort
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: locg-service
  ports:
    - name: ws-locg
      port: 8080