// Copyright © 2024 FuryLion Group LLC. All Rights Reserved.
//
// Unauthorized copying of this file, via any medium is strictly prohibited
// without the express permission of FuryLion Group LLC.
// Proprietary and confidential.

// Code generated by network-gen. DO NOT EDIT.
// source: proto/handlers.network

package errors

import "errors"

// ErrUnexpectedError is an error that occurs when an unknown error occurs for unknown reasons.
var ErrUnexpectedError = errors.New("UnexpectedError")

var ErrAuthChallengeNotFound = errors.New("AuthChallengeNotFound")

var ErrInvalidSignature = errors.New("InvalidSignature")

var ErrInvalidToken = errors.New("InvalidToken")

var ErrInsufficientNumberOfCardsInDeck = errors.New("InsufficientNumberOfCardsInDeck")

// ErrAccountNotFound error that occurs when the required account is not found.
var ErrUserNotFound = errors.New("UserNotFound")

var ErrNotAuthorized = errors.New("NotAuthorized")

var ErrUserNotConfirmed = errors.New("UserNotConfirmed")

// ErrOperationIsProhibited error that occurs when creating an action that is prohibited from doing
// For example: an operation is being performed that is only allowed in the test environment.
var ErrOperationIsProhibited = errors.New("OperationIsProhibited")

// ErrSessionNotFound error that occurs when session data is not found.
// Re-login required.
var ErrSessionNotFound = errors.New("SessionNotFound")

var ErrPlayerMovesOutOfTurn = errors.New("PlayerMovesOutOfTurn")

var ErrInvalidCard = errors.New("InvalidCard")

var ErrCellIsAlreadyOccupied = errors.New("CellIsAlreadyOccupied")

var ErrCannotAttack = errors.New("CannotAttack")

var ErrInvalidDeck = errors.New("InvalidDeck")

var ErrMatchNotFound = errors.New("MatchNotFound")

var ErrRequestAlreadySent = errors.New("RequestAlreadySent")

var ErrRequestNotFound = errors.New("RequestNotFound")

var ErrAlreadyYourFriend = errors.New("AlreadyYourFriend")

var ErrAlreadyHaveAnIncomingRequest = errors.New("AlreadyHaveAnIncomingRequest")

var ErrPlayersFriendsListIsFull = errors.New("PlayersFriendsListIsFull")

var ErrPlayerAlreadyEnteredTheArena = errors.New("PlayerAlreadyEnteredTheArena")

var ErrArenaOpponentNotFound = errors.New("ArenaOpponentNotFound")

var ErrYouAreNotInTheArena = errors.New("YouAreNotInTheArena")

var ErrMissionIsLocked = errors.New("MissionIsLocked")

var ErrZeroWalletAddress = errors.New("ZeroWalletAddress")

var ErrNotEnoughResources = errors.New("NotEnoughResources")

var ErrTrophyRoadRewardAlreadyClaimed = errors.New("TrophyRoadRewardAlreadyClaimed")

var ErrTrophyRoadRewardNotFound = errors.New("TrophyRoadRewardNotFound")

var ErrStoryModeIsNotCompleted = errors.New("StoryModeIsNotCompleted")

var ErrPlayerIsNotOnline = errors.New("PlayerIsNotOnline")

var ErrProductNotFound = errors.New("ProductNotFound")

var ErrOrderAlreadyPaid = errors.New("OrderAlreadyPaid")

var ErrInvalidOrderStatus = errors.New("InvalidOrderStatus")

var ErrProductNotAvailable = errors.New("ProductNotAvailable")

var ErrWithdrawalAmountIsLowerThanRequired = errors.New("WithdrawalAmountIsLowerThanRequired")

var ErrWithdrawalLimitExceeded = errors.New("WithdrawalLimitExceeded")

var ErrMaintenanceMode = errors.New("MaintenanceMode")

var ErrWithdrawalIsNotAvailableYet = errors.New("WithdrawalIsNotAvailableYet")

var ErrProductIsSoldOut = errors.New("ProductIsSoldOut")

var ErrDuplicateWallet = errors.New("DuplicateWallet")

var ErrWalletAlreadyAttched = errors.New("WalletAlreadyAttched")

var ErrorsByCode = map[error]uint16 {
	ErrUnexpectedError: 0,
	ErrAuthChallengeNotFound: 1,
	ErrInvalidSignature: 2,
	ErrInvalidToken: 3,
	ErrInsufficientNumberOfCardsInDeck: 4,
	ErrUserNotFound: 5,
	ErrNotAuthorized: 6,
	ErrUserNotConfirmed: 7,
	ErrOperationIsProhibited: 8,
	ErrSessionNotFound: 9,
	ErrPlayerMovesOutOfTurn: 10,
	ErrInvalidCard: 11,
	ErrCellIsAlreadyOccupied: 12,
	ErrCannotAttack: 13,
	ErrInvalidDeck: 14,
	ErrMatchNotFound: 15,
	ErrRequestAlreadySent: 16,
	ErrRequestNotFound: 17,
	ErrAlreadyYourFriend: 18,
	ErrAlreadyHaveAnIncomingRequest: 19,
	ErrPlayersFriendsListIsFull: 20,
	ErrPlayerAlreadyEnteredTheArena: 21,
	ErrArenaOpponentNotFound: 22,
	ErrYouAreNotInTheArena: 23,
	ErrMissionIsLocked: 24,
	ErrZeroWalletAddress: 25,
	ErrNotEnoughResources: 26,
	ErrTrophyRoadRewardAlreadyClaimed: 27,
	ErrTrophyRoadRewardNotFound: 28,
	ErrStoryModeIsNotCompleted: 29,
	ErrPlayerIsNotOnline: 30,
	ErrProductNotFound: 31,
	ErrOrderAlreadyPaid: 32,
	ErrInvalidOrderStatus: 33,
	ErrProductNotAvailable: 34,
	ErrWithdrawalAmountIsLowerThanRequired: 35,
	ErrWithdrawalLimitExceeded: 36,
	ErrMaintenanceMode: 37,
	ErrWithdrawalIsNotAvailableYet: 38,
	ErrProductIsSoldOut: 39,
	ErrDuplicateWallet: 40,
	ErrWalletAlreadyAttched: 41,
}